version: "3.4"
services:
 vending_machine:
   image: node:18-alpine
   container_name: vending_machine
   entrypoint: /bin/sh
   ports:
     - 3000:3000
   working_dir: /srv/app
   volumes:
     - type: bind
       source: ./
       target: /srv/app
   tty: true